# Generated by Django 3.0.8 on 2020-07-28 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
