# Generated by Django 3.0.8 on 2020-08-05 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_auto_20200805_1220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='post',
            new_name='post_id',
        ),
    ]
